name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      - name: Echo Username from Secret
        run:
          echo "Username: ${{ secrets.USERNAME }}"

      - name: Set Sonatype Credentials
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret
        run: echo "Sonatype credentials set"  # Optional for confirmation (won't be visible)

      - name: Get Version Info with Specific Commits (using custom task)
        # Pass numCommits from workflow to Gradle task as a property
        run: ./gradlew getVersion -PnumCommits=${{ github.event.commits }}

      # Optional: Get Current Version (consider modifying for clarity)
      - name: Get Current Version (optional)
        id: get_version  # Assuming the task sets a 'numCommits' property after filtering
        run: echo "::set-output name=CURRENT_VERSION=$(./gradlew properties -q | grep numCommits | cut -d= -f2)"

      - name: Build and Test (Java Specific)
        run: ./gradlew test

      - name: Publish
        run: ./gradlew publish -DskipTests