name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew


      - name: Get Commit Count
        id: commit_count
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/branches/:branch
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          branch: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Commit Count
        run:
          echo "TEST"

      - name: Get Version Info with Specific Commits (using custom task)
        # Pass numCommits from workflow to Gradle task as an environment variable
        env:
          GITHUB_COMMITS: ${{ github.event.commits.length }}
        run: ./gradlew getVersion


      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret\
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret\
        run: ./gradlew publish -DskipTests