name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Get Version Info (using custom task)
        run: ./gradlew getVersion

      - name: Build and Test (Java Specific)
        run: ./gradlew test

      - name: Publish
        run: ./gradlew publish -DskipTests