name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      - name: Get Version Info with Specific Commits (using custom task)
        # Pass numCommits from workflow to Gradle task as an environment variable
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret
          GITHUB_COMMITS: ${{ github.event.commits }}
          NUM_COMMITS: ${{ github.event.commits.length }}  # Calculate numCommits
        run: ./gradlew getVersion


      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret\
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret\
        run: ./gradlew publish -DskipTests