name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew


      - name: Get commit count for entire branch (public repo)
        run: |
          url="https://api.github.com/repos/${{ github.repository }}/commits?sha=${{ github.base_ref }}"
          response=$(curl -sSL "$url")
          echo "## The branch has $(echo "$response" | jq '. | length')"  # Parse JSON with jq

      - name: Get Version Info with Specific Commits (using custom task)
        # Pass numCommits from workflow to Gradle task as an environment variable
        env:
          GITHUB_COMMITS: ${{ github.event.commits.length }}
        run: ./gradlew getVersion


      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret\
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret\
        run: ./gradlew publish -DskipTests