name: Bump Patch and Publish (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      # Modified command (assuming gradlew script is executable)
      - name: Increase Version with Commits
        run: ./gradlew -q properties --properties com.example.version=$(git describe --always --abbrev=6)

      # Optional: Get Current Version (consider modifying for clarity)
      - name: Get Current Version
        id: get_version
        run: echo "::set-output name=CURRENT_VERSION=$(./gradlew properties -q | grep version | cut -d= -f2)"

      - name: Build and Test (Java Specific)
        run: ./gradlew test

      - name: Publish
        run: ./gradlew publish -DskipTests
